/**
 * Builds supabase/setup.sql = tables + seed content (from data/) + triggers/policies.
 * Seed goes in before the triggers exist so the counters in the mock data are kept as-is.
 *
 *   npx tsx scripts/build-sql.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { LOOKALIKE_FROM, LOOKALIKE_TO, RULES } from "../lib/contentFilter";
import { assets } from "../data/assets";
import { communities } from "../data/communities";
import { comments, news, posts } from "../data/posts";
import { topics } from "../data/topics";
import { users } from "../data/users";

// The mock "me" account is replaced by real sign-ups, so its content moves to seed members.
const REASSIGN: Record<string, string> = { u_javed: "u_ananya" };
const who = (id: string) => REASSIGN[id] ?? id;

const q = (v: string | number | boolean | null | undefined) => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${v.replace(/'/g, "''")}'`;
};
const arr = (a: string[]) => `array[${a.map(q).join(", ")}]::text[]`;
const ago = (min: number) => `now() - interval '${Math.round(min)} minutes'`;

const seedUsers = users.filter((u) => u.id !== "u_javed");
const out: string[] = [];
const insert = (table: string, cols: string[], rows: string[][]) => {
  if (!rows.length) return;
  out.push(`insert into public.${table} (${cols.join(", ")}) values\n${rows.map((r) => `  (${r.join(", ")})`).join(",\n")}\non conflict do nothing;\n`);
};

out.push("-- ============================================================\n-- Seed content (generated by scripts/build-sql.ts)\n-- ============================================================\n");

insert("assets", ["id", "ticker", "name", "exchange", "region", "sector", "about", "themes"], assets.map((a) => [q(a.id), q(a.ticker), q(a.name), q(a.exchange), q(a.region), q(a.sector), q(a.about), arr(a.themes)]));
insert("topics", ["slug", "name", "kind", "description"], topics.map((t) => [q(t.slug), q(t.name), q(t.kind), q(t.description)]));
insert(
  "communities",
  ["slug", "name", "kind", "region", "tagline", "hue", "members", "discussions", "asset_id", "featured", "logo_url"],
  communities.map((c) => [q(c.slug), q(c.name), q(c.kind), q(c.region), q(c.tagline), q(c.hue), q(0), q(0), q(c.assetId), q(!!c.featured), q(c.logoUrl)]),
);
insert(
  "profiles",
  ["id", "username", "name", "bio", "hue", "reputation", "tier", "followers", "following", "discussions", "comments", "helpful", "verified", "avatar_url"],
  seedUsers.map((u) => [q(u.id), q(u.username), q(u.name), q(u.bio), q(u.hue), q(u.reputation), q(u.tier), q(u.followers), q(u.following), q(u.contributions.discussions), q(u.contributions.comments), q(u.contributions.helpful), q(!!u.verified), q(u.avatarUrl)]),
);
insert(
  "community_members",
  ["user_id", "community_slug"],
  seedUsers.flatMap((u) => u.communities.map((c) => [q(u.id), q(c)])),
);
insert(
  "posts",
  ["id", "author_id", "community_slug", "topics", "type", "stance", "title", "body", "has_image", "likes", "comments", "created_at"],
  posts.map((p) => [q(p.id), q(who(p.authorId)), q(p.communitySlug), arr(p.topics), q(p.type), q(p.stance), q(p.title), q(p.body), q(!!p.hasImage), q(p.likes), q(p.comments), ago(p.ageMin)]),
);
const polls = posts.filter((p) => p.poll);
insert("polls", ["post_id", "question", "ends_at"], polls.map((p) => [q(p.id), q(p.poll!.question), "null"]));
insert(
  "poll_options",
  ["post_id", "id", "label", "votes", "position"],
  polls.flatMap((p) => p.poll!.options.map((o, i) => [q(p.id), q(o.id), q(o.label), q(o.votes), q(i + 1)])),
);
// Parents must exist before replies.
const sortedComments = [...comments].sort((a, b) => Number(!!a.parentId) - Number(!!b.parentId));
insert(
  "comments",
  ["id", "post_id", "author_id", "parent_id", "body", "likes", "created_at"],
  sortedComments.map((c) => [q(c.id), q(c.postId), q(who(c.authorId)), q(c.parentId), q(c.body), q(c.likes), ago(c.ageMin)]),
);
insert("news", ["id", "community_slug", "source", "headline", "discussion_count", "created_at"], news.map((n) => [q(n.id), q(n.communitySlug), q(n.source), q(n.headline), q(n.discussionCount), ago(n.ageMin)]));

// content_violation(): the database-side copy of lib/contentFilter.ts (the client copy is only for instant feedback).
const checks = RULES.map((r) => {
  const subject = r.normalize ? "n" : "t";
  const cond = r.patterns.map((pat) => `${subject} ~* ${q(pat)}`).join("\n     or ");
  return `  if ${cond} then\n    return ${q(r.code)};\n  end if;`;
}).join("\n");
const contentFn = `-- ============================================================
-- Content rules (generated from lib/contentFilter.ts)
-- ============================================================

create or replace function public.content_violation(p_text text) returns text
language plpgsql immutable as $$
declare
  t text := coalesce(p_text, '');
  n text := translate(lower(coalesce(p_text, '')), ${q(LOOKALIKE_FROM)}, ${q(LOOKALIKE_TO)});
begin
${checks}
  return null;
end $$;
`;

const sql = [readFileSync("supabase/tables.sql", "utf8"), out.join("\n"), contentFn, readFileSync("supabase/logic.sql", "utf8")].join("\n");
writeFileSync("supabase/setup.sql", sql);
console.log(`supabase/setup.sql written (${sql.length} bytes)`);
