/**
 * Builds supabase/nifty50_reset.sql: wipes every community and asset, then seeds the NIFTY 50 index
 * and its 50 stocks. Destructive: posts, comments, news, memberships and mood votes go with the communities.
 *
 *   npm run db:nifty
 */
import { writeFileSync } from "node:fs";
import { FEATURED, NIFTY_INDEX, nifty50 } from "../data/nifty50";

const q = (v: string | number | boolean | null) => {
  if (v === null) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${v.replace(/'/g, "''")}'`;
};
const slugOf = (s: string) => s.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const hueOf = (s: string) => [...s].reduce((h, c) => (h * 31 + c.charCodeAt(0)) % 360, 7);
const logo = (domain: string) => `https://icon.horse/icon/${domain}`;
const firstSentence = (s: string) => s.split(". ")[0].replace(/\.$/, "") + ".";

const assetRows: string[] = [];
const communityRows: string[] = [];

const idx = NIFTY_INDEX;
assetRows.push(`(${[q(idx.slug), q(idx.ticker), q(idx.name), q("NSE"), q("india"), q(idx.sector), q(idx.about), "'{}'::text[]", q(idx.priceSymbol)].join(", ")})`);
communityRows.push(`(${[q(idx.slug), q(idx.name), q("market"), q("india"), q(firstSentence(idx.about)), hueOf(idx.slug), 0, 0, q(idx.slug), "true", q(logo(idx.domain))].join(", ")})`);

for (const s of nifty50) {
  const slug = slugOf(s.ticker);
  assetRows.push(`(${[q(slug), q(s.ticker), q(s.name), q("NSE"), q("india"), q(s.sector), q(s.about), "'{}'::text[]", q(`${s.ticker}.NS`)].join(", ")})`);
  communityRows.push(`(${[q(slug), q(s.name), q("asset"), q("india"), q(s.about), hueOf(slug), 0, 0, q(slug), q(FEATURED.has(s.ticker)), q(logo(s.domain))].join(", ")})`);
}

const sql = `-- NIFTY 50 reset. GENERATED by scripts/build-nifty.ts. Do not edit by hand.
-- DESTRUCTIVE: removes every community and asset, and with them all discussions, comments, news,
-- memberships and mood votes. Run supabase/admin_communities.sql first.
begin;

delete from public.communities;
delete from public.assets;

insert into public.assets (id, ticker, name, exchange, region, sector, about, themes, price_symbol) values
${assetRows.join(",\n")};

insert into public.communities (slug, name, kind, region, tagline, hue, members, discussions, asset_id, featured, logo_url) values
${communityRows.join(",\n")};

commit;
`;
writeFileSync("supabase/nifty50_reset.sql", sql);
console.log(`supabase/nifty50_reset.sql written: 1 index + ${nifty50.length} stocks`);
